name: Development

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore $project_path
      env:
        project_path: Snake
    - name: Build
      run: dotnet build $project_path --configuration Release --no-restore
    - name: Test
      run: dotnet test $project_path --no-restore --verbosity normal
